apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.roleName }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "get"]
