apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dilafar/django-admin-deployment.git
    path: helm
    targetRevision: main
    helm:
      valueFiles:
        - charts/djangoapp/values.yaml
        - charts/postgresdb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true