apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data: 
  postgres_init.sql: |-
    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
    GRANT ALL PRIVILEGES ON SCHEMA public TO docker;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO docker;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO docker;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO docker;
